### ISSUE TITLE
API isn't responsive

### ISSUE THREAD

**Issue by waldoj** [Code4HR/business-openva-api#11]
My `config.json` file looks like this:

```json
{
  "host": "vabusinesses.org",
  "port": 3000,
  "elasticSearch": {
    "host": "127.0.0.1:9200"
  }
}
```

Running `api.js` yields this:

```
$ node api.js
Server running at:  http://ip-10-0-0-240:3000
```

And connecting to port 3000 produces this:

```
$ telnet localhost 3000 
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET /businesses
```

Nothing is ever returned in response to `GET /businesses`. There aren't any log files to check, so I confess I'm at a loss. Any suggestions?

**Comment by ttavenner** [comment]
The server as written won't respond to telnet requests. I just tested my local version to confirm. It will however respond to curl requests and web requests. You do bring up a good point about logging. I will work on adding support for an actual log file for diagnosing other issues. It will log errors to console but not currently to a more permanent source.

**Comment by waldoj** [comment]
Oh, that's interesting! Yes, a cURL request works great. Thanks!
