### ISSUE TITLE
Config file host name is ignored

### ISSUE THREAD

**Issue by waldoj** [Code4HR/business-openva-api#12]
I _think_ it's ignoring the host name. My `config.json` file looks like this:

```json
{
  "host": "vabusinesses.org",
  "port": 3000,
  "elasticSearch": {
    "host": "127.0.0.1:9200"
  }
}
```

But when I fire up the API, I get this:

```
$ node api.js
Server running at:  http://ip-10-0-0-240:3000
```

Shouldn't it say that the server is running at `http://vabusinesses.org:3000`? (Or is this a cosmetic problem, and not a functional problem?)

**Comment by ttavenner** [comment]
You are right. I had completely left out the host when starting the server. I just pushed a fix.
