### ISSUE TITLE
EADDRNOTAVAIL error when domain specified as host

### ISSUE THREAD

**Issue by waldoj** [Code4HR/business-openva-api#13]
With the changes in 348c16c3a4d5c44c2a937600783e18da68fac6a2, with `host` in `config.json` set to `vabusinesses.org`, launching `api.js` now fails with this error:

```
$ node api.js
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRNOTAVAIL
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1112:19)
    at listen (net.js:1155:10)
    at net.js:1253:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:81:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:99:10)
```

I do not get this error if I set `host` to `localhost`.

I don't know if this error is consequential. That is, I don't know if the API will ever self-report its own address as `localhost` instead of as `vabusinesses.org`, or whether it only respond to internal requests (and not requests that originate externally) as a result of this. If these aren't problems, then presumably this is a pretty minor bug.

**Comment by ttavenner** [comment]
Ah, I think I see I may see the issue. the API doesn't know how to lookup the address to get the IP. To have it listen externally you've got a couple of options. You can open up a specific port in IPTABLES (i.e. 3000) for 0.0.0.0 and then set the host on `config.json` to 0.0.0.0. This tells the firewall to allow this port for all IP addresses and also tells the API to listen on all IP addresses. This should then make it available at vabusinesses.org:3000

Alternatively if you would like it to be accessible at a specific host without a special port(i.e. api.vabusinesses.org, or vabusinesses.org/api), then you would keep the host in `config.json` set to localhost and configure a proxy pass on your web server. Your web server would then redirect requests from external sources to the API internally. I can give you examples for this depending on what your front end webserver is (i.e Apache/NginX). Here are a couple of links on the issue:
http://thatextramile.be/blog/2012/01/hosting-a-node-js-site-through-apache/
http://www.sitepoint.com/configuring-nginx-ssl-node-js/

**Comment by waldoj** [comment]
Got it. I'll keep it at `localhost`/`3000` and just proxy it through Apache. (I only have very limited Node experience!) Thank you!

**Comment by ttavenner** [comment]
No problem. It wasn't that long ago that I had very limited Node experience. Since Node essentially runs as its own daemon on the server, listening and responding to requests you will want something to manage the process and keep it running using Linux's built in process management. There are two Node packages that are popular for this purpose: [Forever](https://github.com/foreverjs/forever) and [PM2](https://github.com/Unitech/pm2). Both are very simple to set up and essentially set it and forget it. I'm partial to PM2 for it's more user friendly monitoring.

**Comment by waldoj** [comment]
I installed PM2 and it's running now. I don't see any way that could have been easier.
